# Generated by Django 5.2.8 on 2025-11-22 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_shippingaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='neighborhood',
            field=models.CharField(blank=True, max_length=100, verbose_name='bairro'),
        ),
    ]
